import 'package:flutter/material.dart';
import 'package:font_awesome_flutter/font_awesome_flutter.dart';
import 'package:kdbx/kdbx.dart';

IconData kdbxIconToFlutter(KdbxIcon? icon) {
  switch (icon) {
    case KdbxIcon.Key:
      return Icons.key;
    case KdbxIcon.World:
      return Icons.language;
    case KdbxIcon.Warning:
      return Icons.warning_amber;
    case KdbxIcon.NetworkServer:
      return Icons.dns;
    case KdbxIcon.MarkedDirectory:
      return Icons.bookmark;
    case KdbxIcon.UserCommunication:
      return Icons.forum;
    case KdbxIcon.Parts:
      return Icons.settings_suggest;
    case KdbxIcon.Notepad:
      return Icons.note;
    case KdbxIcon.WorldSocket:
      return Icons.wifi;
    case KdbxIcon.Identity:
      return Icons.badge;
    case KdbxIcon.PaperReady:
      return Icons.description;
    case KdbxIcon.Digicam:
      return Icons.camera_alt;
    case KdbxIcon.IRCommunication:
      return Icons.settings_remote;
    case KdbxIcon.MultiKeys:
      return Icons.vpn_key;
    case KdbxIcon.Energy:
      return Icons.bolt;
    case KdbxIcon.Scanner:
      return Icons.scanner;
    case KdbxIcon.WorldStar:
      return Icons.public;
    case KdbxIcon.CDRom:
      return Icons.album;
    case KdbxIcon.Monitor:
      return Icons.computer;
    case KdbxIcon.EMail:
      return Icons.email;
    case KdbxIcon.Configuration:
      return Icons.settings;
    case KdbxIcon.ClipboardReady:
      return Icons.content_paste;
    case KdbxIcon.PaperNew:
      return Icons.note_add;
    case KdbxIcon.Screen:
      return Icons.tv;
    case KdbxIcon.EnergyCareful:
      return Icons.eco;
    case KdbxIcon.EMailBox:
      return Icons.mail;
    case KdbxIcon.Disk:
      return Icons.storage;
    case KdbxIcon.Drive:
      return Icons.storage;
    case KdbxIcon.PaperQ:
      return Icons.find_in_page;
    case KdbxIcon.TerminalEncrypted:
      return Icons.terminal;
    case KdbxIcon.Console:
      return Icons.code;
    case KdbxIcon.Printer:
      return Icons.print;
    case KdbxIcon.ProgramIcons:
      return Icons.apps;
    case KdbxIcon.Run:
      return Icons.play_arrow;
    case KdbxIcon.Settings:
      return Icons.settings;
    case KdbxIcon.WorldComputer:
      return Icons.desktop_windows;
    case KdbxIcon.Archive:
      return Icons.archive;
    case KdbxIcon.Homebanking:
      return Icons.account_balance;
    case KdbxIcon.DriveWindows:
      return Icons.window;
    case KdbxIcon.Clock:
      return Icons.access_time;
    case KdbxIcon.EMailSearch:
      return Icons.mark_email_read;
    case KdbxIcon.PaperFlag:
      return Icons.flag;
    case KdbxIcon.Memory:
      return Icons.memory;
    case KdbxIcon.TrashBin:
      return Icons.delete;
    case KdbxIcon.Note:
      return Icons.sticky_note_2;
    case KdbxIcon.Expired:
      return Icons.event_busy;
    case KdbxIcon.Info:
      return Icons.info;
    case KdbxIcon.Package:
      return Icons.inventory_2;
    case KdbxIcon.Folder:
      return Icons.folder;
    case KdbxIcon.FolderOpen:
      return Icons.folder_open;
    case KdbxIcon.FolderPackage:
      return Icons.folder_special;
    case KdbxIcon.LockOpen:
      return Icons.lock_open;
    case KdbxIcon.PaperLocked:
      return Icons.lock;
    case KdbxIcon.Checked:
      return Icons.check_circle;
    case KdbxIcon.Pen:
      return Icons.edit;
    case KdbxIcon.Thumbnail:
      return Icons.image;
    case KdbxIcon.Book:
      return Icons.book;
    case KdbxIcon.List:
      return Icons.list;
    case KdbxIcon.UserKey:
      return Icons.person;
    case KdbxIcon.Tool:
      return Icons.build;
    case KdbxIcon.Home:
      return Icons.home;
    case KdbxIcon.Star:
      return Icons.star;
    case KdbxIcon.Tux:
      return FontAwesomeIcons.linux;
    case KdbxIcon.Feather:
      return FontAwesomeIcons.feather;
    case KdbxIcon.Apple:
      return FontAwesomeIcons.apple;
    case KdbxIcon.Wiki:
      return Icons.menu_book;
    case KdbxIcon.Money:
      return Icons.attach_money;
    case KdbxIcon.Certificate:
      return Icons.verified;
    case KdbxIcon.BlackBerry:
      return Icons.phone_android;
    case null:
      return Icons.key;
  }
}
